---
title: "Life Chart"
subtitle: "A tile chart of my life"
summary:  "A tile chart of my life"
author: "Derek Michael Wright <wrightmderek@gmail.com> [www.dblogr.com/](https://dblogr.netlify.com/)"
date: "2020-03-01"
categories: [ "dblogr" ]
tags: [ "dblogr",  "Personal", "R" ]
draft: true
image:
  preview_only: yes
links:
  - icon: chart-line
    icon_pack: fas
    name: All Graphs
    url: dblogr_graphs/life_chart
  - icon: file-code
    icon_pack: far
    name: HTML
    url: https://derekmichaelwright.github.io/htmls/dblogr/life_chart.html
  - icon: file-pdf
    icon_pack: far
    name: PDF (Save/Print)
    url: dblogr_pdfs/life_chart.pdf
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```

---

```{r eval = F}
library(dblogr)
library(lubridate)
library(waffle)
library(hrbrthemes)
library(extrafont)
#loadfonts(device = "win", quiet = TRUE)

# Create the data-----
life_data <- data.frame(months = factor(rep(month.abb[1:12], 81), levels=month.abb[1:12]),
                        Year = rep(1989:(1989+80), each = 12)) %>%
  slice(8:nrow(.)) %>%  ## remove months before my birth month (August)
  mutate(age = rep(0:80, each = 12, length.out = nrow(.))) %>% 
  rowid_to_column("row_name")  ## add column for row number

## add the "eras" to be colored in the waffle chart
life_data <- life_data %>%
  mutate(era = fct_inorder(case_when(
    row_name < 30 ~ "Childhood - Canada",
    row_name < 111 ~ "Childhood - US",
    row_name < 182 ~ "Childhood - Canada",
    row_name < 219 ~ "Highschool - Regina, SK",
    row_name < 282 ~ "University of Regina - BSc. Biology",
    row_name < 310 ~ "University of Geissen - MSc. Agrobiotechnology",
    row_name < 375 ~ "University of Saskatchewan - Research Assistant",
    TRUE ~ "Time left")))


ggplot(life_data) +
  geom_waffle(aes(fill = era))

waffle(life_data$era)
# Waffle chart-----
life_in_months <- life_data %>%
  count(era) %>% ## the count of each era is the number of months in that era
  ggplot(aes(fill = era, values = n)) +
  geom_waffle(color = "#F7F7F7", n_rows = 12, size = 1, flip = TRUE) + ## make each row a year/12 months
  scale_fill_manual(name = "", values = c("#EF476F","#FCA311","#FFD166","#0EAD69","#4ECDC4","#118AB2")) +  ## assign colors to the eras
  coord_equal() +
  theme_ipsum(grid = "") +
  theme(legend.text = element_text(family = "Cooper Lt BT", size = 40),
        plot.background = element_rect(fill = "#F7F7F7", color = "#F7F7F7")) +
  theme_enhance_waffle()

life_in_months

# Save the chart
life_in_months + ggsave("life_in_months.png", device = "png", type = "cairo", width = 15, height = 25, dpi = 300)
```
